name: integracion continua con node.js

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar el repositorio
      uses: actions/checkout@v4J
      
    - name: Instalacion de NodeJS 
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: ejecucion del testing    
    - run: npm install
    - run: npm ci
    - run: npm install --save-dev jest
    - run: npm test

